package com.hoangnt391.automessenger;

/**
 * Compatibility facade kept so the rest of AutoMessenger keeps the same flow.
 * Gemini HTTP/API calls have been removed. Answers are generated by the
 * installed ChatGPT app through the existing AccessibilityService.
 */
public final class AiClient {
    private AiClient() {}

    public static String reply(String ignoredKey, String ignoredModel,
                               String instructions, String incoming) throws Exception {
        MessageAccessibilityService service = MessageAccessibilityService.getInstance();
        if (service == null) {
            throw new IllegalStateException("Chưa bật Trợ năng.");
        }
        return service.requestChatGptReply(instructions, incoming);
    }

    public static void validateKey(String ignoredKey, String ignoredModel) {
        // Kept for source compatibility. ChatGPT web/app automation does not use an API key.
    }
}
